name: Create website
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      IMGVERSION:
        description: 'Version of the docker image to use'
        required: false
        default: 'latest'

jobs:
  create-website:
    runs-on: ubuntu-latest
    env: 
        CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        IMGVERSION: 2024-05-15
    if: "!contains(github.event.head_commit.message, '[skipci]')"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - name: Make executable
        run: "chmod +x ./_build.sh"
      - name: Set version for docker image
        id: imgversion
        run: |
          USER_INPUT=${{ github.event.inputs.IMGVERSION }}
          echo "::set-output IMGVERSION=value::${USER_INPUT:-"${{ env.IMGVERSION }}"}"
      # Runs a set of commands using the runners shell
      - name: Run docker for R 
        uses: docker://larsvilhuber/nber-presentation:${{ github.steps.imgversion.output }} 
        with:
          args: "/github/workspace/_build.sh "
          
          
      # send it to gh-pages
      # Remember to give the "action-bot" write permissions under "Actions" (in Settings)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: .
           user_name: 'Github Action Bot'
           user_email: 'lars.vilhuber@cornell.edu'
           publish_branch: gh-pages 
           keep_files: true
